version: "3.9"

# 网络配置
networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  nginx:
    image: nginx:latest
    environment:
      - TZ=${TZ}
    privileged: true
    volumes:
      - ${ETC_PATH_HOST}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${ETC_PATH_HOST}/nginx/conf.d/:/etc/nginx/conf.d/
      - ${ETC_PATH_HOST}/nginx/certificate/:/etc/nginx/certificate/
      - ${DATA_PATH_HOST}/nginx/log/:/var/log/nginx/
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    networks:
      - backend
    restart: always

  mysql:
    image: mysql:8.0.26
    environment:
      - TZ=${TZ}
      - MYSQL_USER=${MYSQL_USERNAME}                  # 设置 Mysql 用户名称
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}              # 设置 Mysql 用户密码
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}    # 设置 Mysql root 用户密码
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql        # 引用 .env 配置中 DATA_PATH_HOST 变量，将宿主机上存放 Mysql 数据的目录挂载到容器中 /var/lib/mysql 目录
    ports:
      - "${MYSQL_PORT}:3306"                          # 设置容器3306端口映射指定宿主机端口
    networks:
      - backend
    restart: always

  redis:
    image: redis:6.2.5
    environment:
      - TZ=${TZ}
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/redis:/data                 # 引用 .env 配置中 DATA_PATH_HOST 变量，将宿主机上存放 Redis 数据的目录挂载到容器中 /data 目录
    ports:
      - "${REDIS_PORT}:6379"                          # 设置容器6379端口映射指定宿主机端口
    networks:
      - backend
    restart: always

  etcd:
    image: bitnami/etcd:3.5.2
    environment:
      - TZ=${TZ}
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:                               # 设置端口映射
      - "${ETCD_PORT}:2379"
    networks:
      - backend
    restart: always

  prometheus:
    image: bitnami/prometheus:latest
    environment:
      - TZ=${TZ}
    privileged: true
    volumes:
      - ./etc/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml  # 将 prometheus 配置文件挂载到容器里
      - ${DATA_PATH_HOST}/prometheus:/opt/bitnami/prometheus/data
    ports:
      - "${PROMETHEUS_PORT}:9090"                     # 设置容器9090端口映射指定宿主机端口，用于宿主机访问可视化web
    networks:
      - backend
    restart: always

  grafana:
    image: grafana/grafana:latest
    environment:
      - TZ=${TZ}
    privileged: true
    volumes:
      - ./etc/grafana.ini:/etc/grafana/grafana.ini   # 将配置文件挂载到容器里
      - ${DATA_PATH_HOST}/grafana:/var/lib/grafana
    ports:
      - "${GRAFANA_PORT}:3000"                        # 设置容器3000端口映射指定宿主机端口，用于宿主机访问可视化web
    networks:
      - backend
    restart: always
